# Cart2Insights — Data Understanding

**Project:** Cart2Insights: Decoding E-Commerce Performance

**Purpose:** Understand the business context, dataset structure, table
relationships, keys, grain, and analytical role of each dataset before
performing data quality analysis and transformations.

## 1. Project Objective

Cart2Insights is an e-commerce analytics project that aims to uncover
meaningful business insights from multiple related datasets.

The analysis focuses on:

- Sales and revenue
- Customer behavior
- Product performance
- Seller performance
- Payment behavior
- Delivery performance
- Customer satisfaction

The overall goal is to transform raw e-commerce data into meaningful
business insights and actionable recommendations.

### ER Diagram

![ER Diagram](..\data\raw\ER_Diagram_Cart2Insights.png)

In [6]:
import pandas as pd
import sys
sys.path.insert(0, "../src")
from data_loader import load_datasets

In [7]:
raw = "../data/raw/"
datasets = load_datasets(raw)

In [8]:
dataset_overview = pd.DataFrame(
    {
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
    }
    for name, df in datasets.items()
)

dataset_overview

                          table     rows  columns
0                     customers    99441        5
1                        orders    99441        8
2                   order_items   112650        7
3                order_payments   103886        5
4                 order_reviews    99224        7
5                      products    32951        9
6                       sellers     3095        4
7                   geolocation  1000163        5
8  product_category_translation       71        2

## Data Types

In [9]:
for name, df in datasets.items():
    print(f"\n{'=' * 70}")
    print(f"TABLE: {name}")
    print(f"{'=' * 70}")
    print(df.dtypes)

======================================================================
TABLE: customers
======================================================================
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

======================================================================
TABLE: orders
======================================================================
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

======================================================================
TABLE: order_items
======================================================================
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

======================================================================
TABLE: order_payments
======================================================================
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

======================================================================
TABLE: order_reviews
======================================================================
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

======================================================================
TABLE: products
======================================================================
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

======================================================================
TABLE: sellers
======================================================================
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

======================================================================
TABLE: geolocation
======================================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

======================================================================
TABLE: product_category_translation
======================================================================
product_category_name            str
product_category_name_english    str
dtype: object

In [10]:
for name, df in datasets.items():
    print(f"\n{'=' * 100}")
    print(f"TABLE: {name}")
    display(df.head())

====================================================================================================
TABLE: customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

====================================================================================================
TABLE: orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

====================================================================================================
TABLE: order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

====================================================================================================
TABLE: order_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

====================================================================================================
TABLE: order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

====================================================================================================
TABLE: products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

====================================================================================================
TABLE: sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

====================================================================================================
TABLE: geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

====================================================================================================
TABLE: product_category_translation

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## Dataset Shape

In [11]:
for name, df in datasets.items():
    print(f"{name} : {df.shape}")

customers : (99441, 5)
orders : (99441, 8)
order_items : (112650, 7)
order_payments : (103886, 5)
order_reviews : (99224, 7)
products : (32951, 9)
sellers : (3095, 4)
geolocation : (1000163, 5)
product_category_translation : (71, 2)

## Dataset Information

In [12]:
for name, df in datasets.items():
    print(f"\n{"--"*15} {name} {"--"*15}")
    print(df.info())

------------------------------ customers ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB
None

------------------------------ orders ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB
None

------------------------------ order_items ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB
None

------------------------------ order_payments ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB
None

------------------------------ order_reviews ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB
None

------------------------------ products ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB
None

------------------------------ sellers ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB
None

------------------------------ geolocation ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB
None

------------------------------ product_category_translation ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 3.5 KB
None

#### Observattion till now
| Customers | orders | order items | order payements | order reviews | products | sellers | geolocation | cat translation| 
| ---       |---     |---          |---              |---            |---       |---      |---          |---             |       
|no missing values|some missing values(not major)|no missing values|no missing values|some missing values(review txt)|some missing values(not major)| no missing values|no missing values|no missing values|
| | needs to convert into datetime| needs to convert into datetime| |datetime conversion| | | | |

## Descriptive Statistics

For numerical columns, `describe()` provides summary statistics such as
count, mean, standard deviation, minimum, quartiles, and maximum.

In [13]:
for name, df in datasets.items():
    print(f"\n{"--"*15} {name} {"--"*15}")
    print(df.describe())

------------------------------ customers ------------------------------
       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

------------------------------ orders ------------------------------
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-03-31 15:08:21  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

------------------------------ order_items ------------------------------
       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

------------------------------ order_payments ------------------------------
       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

------------------------------ order_reviews ------------------------------
       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

------------------------------ products ------------------------------
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000

------------------------------ sellers ------------------------------
       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

------------------------------ geolocation ------------------------------
       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

------------------------------ product_category_translation ------------------------------
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [14]:
for name, df in datasets.items():
    print(f"\n{"--"*15} {name} {"--"*15}")
    print(df.describe(include="all"))

------------------------------ customers ------------------------------
                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        customer_zip_code_prefix customer_city customer_state
count               99441.000000         99441          99441
unique                       NaN          4119             27
top                          NaN     sao paulo             SP
freq                         NaN         15540          41746
mean                35137.474583           NaN            NaN
std                 29797.938996           NaN            NaN
min                  1003.000000           NaN            NaN
25%                 11347.000000           NaN            NaN
50%                 24416.000000           NaN            NaN
75%                 58900.000000           NaN            NaN
max                 99990.000000           NaN            NaN

------------------------------ orders ------------------------------
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-03-31 15:08:21  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

------------------------------ order_items ------------------------------
                                order_id  order_item_id  \
count                             112650  112650.000000
unique                             98666            NaN
top     8272b63d03f5f79c56e9e4120aec44ef            NaN
freq                                  21            NaN
mean                                 NaN       1.197834
std                                  NaN       0.705124
min                                  NaN       1.000000
25%                                  NaN       1.000000
50%                                  NaN       1.000000
75%                                  NaN       1.000000
max                                  NaN      21.000000

                              product_id                         seller_id  \
count                             112650                            112650
unique                             32951                              3095
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0
freq                                 527                              2033
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        shipping_limit_date          price  freight_value
count                112650  112650.000000  112650.000000
unique                93318            NaN            NaN
top     2018-03-01 02:50:48            NaN            NaN
freq                     21            NaN            NaN
mean                    NaN     120.653739      19.990320
std                     NaN     183.633928      15.806405
min                     NaN       0.850000       0.000000
25%                     NaN      39.900000      13.080000
50%                     NaN      74.990000      16.260000
75%                     NaN     134.900000      21.150000
max                     NaN    6735.000000     409.680000

------------------------------ order_payments ------------------------------
                                order_id  payment_sequential payment_type  \
count                             103886       103886.000000       103886
unique                             99440                 NaN            5
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card
freq                                  29                 NaN        76795
mean                                 NaN            1.092679          NaN
std                                  NaN            0.706584          NaN
min                                  NaN            1.000000          NaN
25%                                  NaN            1.000000          NaN
50%                                  NaN            1.000000          NaN
75%                                  NaN            1.000000          NaN
max                                  NaN           29.000000          NaN

        payment_installments  payment_value
count          103886.000000  103886.000000
unique                   NaN            NaN
top                      NaN            NaN
freq                     NaN            NaN
mean                2.853349     154.100380
std                 2.687051     217.494064
min                 0.000000       0.000000
25%                 1.000000      56.790000
50%                 1.000000     100.000000
75%                 4.000000     171.837500
max                24.000000   13664.080000

------------------------------ order_reviews ------------------------------
                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     c444278834184f72b1484dfe47de7f97  c88b1d1b157a9999ce368f218a407141
freq                                   3                                 3
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        review_score review_comment_title review_comment_message  \
count   99224.000000                11568                  40977
unique           NaN                 4527                  36159
top              NaN            Recomendo              Muito bom
freq             NaN                  423                    230
mean        4.086421                  NaN                    NaN
std         1.347579                  NaN                    NaN
min         1.000000                  NaN                    NaN
25%         4.000000                  NaN                    NaN
50%         5.000000                  NaN                    NaN
75%         5.000000                  NaN                    NaN
max         5.000000                  NaN                    NaN

       review_creation_date review_answer_timestamp
count                 99224                   99224
unique                  636                   98248
top     2017-12-19 00:00:00     2017-06-15 23:21:05
freq                    463                       4
mean                    NaN                     NaN
std                     NaN                     NaN
min                     NaN                     NaN
25%                     NaN                     NaN
50%                     NaN                     NaN
75%                     NaN                     NaN
max                     NaN                     NaN

------------------------------ products ------------------------------
                              product_id product_category_name  \
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029
mean                                 NaN                   NaN
std                                  NaN                   NaN
min                                  NaN                   NaN
25%                                  NaN                   NaN
50%                                  NaN                   NaN
75%                                  NaN                   NaN
max                                  NaN                   NaN

        product_name_lenght  product_description_lenght  product_photos_qty  \
count          32341.000000                32341.000000        32341.000000
unique                  NaN                         NaN                 NaN
top                     NaN                         NaN                 NaN
freq                    NaN                         NaN                 NaN
mean              48.476949                  771.495285            2.188986
std               10.245741                  635.115225            1.736766
min                5.000000                    4.000000            1.000000
25%               42.000000                  339.000000            1.000000
50%               51.000000                  595.000000            1.000000
75%               57.000000                  972.000000            3.000000
max               76.000000                 3992.000000           20.000000

        product_weight_g  product_length_cm  product_height_cm  \
count       32949.000000       32949.000000       32949.000000
unique               NaN                NaN                NaN
top                  NaN                NaN                NaN
freq                 NaN                NaN                NaN
mean         2276.472488          30.815078          16.937661
std          4282.038731          16.914458          13.637554
min             0.000000           7.000000           2.000000
25%           300.000000          18.000000           8.000000
50%           700.000000          25.000000          13.000000
75%          1900.000000          38.000000          21.000000
max         40425.000000         105.000000         105.000000

        product_width_cm
count       32949.000000
unique               NaN
top                  NaN
freq                 NaN
mean           23.196728
std            12.079047
min             6.000000
25%            15.000000
50%            20.000000
75%            30.000000
max           118.000000

------------------------------ sellers ------------------------------
                               seller_id  seller_zip_code_prefix seller_city  \
count                               3095             3095.000000        3095
unique                              3095                     NaN         611
top     3442f8959a84dea7ee197c632cb2df15                     NaN   sao paulo
freq                                   1                     NaN         694
mean                                 NaN            32291.059451         NaN
std                                  NaN            32713.453830         NaN
min                                  NaN             1001.000000         NaN
25%                                  NaN             7093.500000         NaN
50%                                  NaN            14940.000000         NaN
75%                                  NaN            64552.500000         NaN
max                                  NaN            99730.000000         NaN

       seller_state
count          3095
unique           23
top              SP
freq           1849
mean            NaN
std             NaN
min             NaN
25%             NaN
50%             NaN
75%             NaN
max             NaN

------------------------------ geolocation ------------------------------
        geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
count                  1.000163e+06     1.000163e+06     1.000163e+06
unique                          NaN              NaN              NaN
top                             NaN              NaN              NaN
freq                            NaN              NaN              NaN
mean                   3.657417e+04    -2.117615e+01    -4.639054e+01
std                    3.054934e+04     5.715866e+00     4.269748e+00
min                    1.001000e+03    -3.660537e+01    -1.014668e+02
25%                    1.107500e+04    -2.360355e+01    -4.857317e+01
50%                    2.653000e+04    -2.291938e+01    -4.663788e+01
75%                    6.350400e+04    -1.997962e+01    -4.376771e+01
max                    9.999000e+04     4.506593e+01     1.211054e+02

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268
mean                NaN               NaN
std                 NaN               NaN
min                 NaN               NaN
25%                 NaN               NaN
50%                 NaN               NaN
75%                 NaN               NaN
max                 NaN               NaN

------------------------------ product_category_translation ------------------------------
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [15]:
for name, df in datasets.items():
    print(f"\n{name}: {list(df.columns)}")

customers: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

orders: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

order_items: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

order_payments: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

order_reviews: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

products: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

sellers: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

geolocation: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

product_category_translation: ['product_category_name', 'product_category_name_english']

## Dataset Overview

| Table | Grain | Purpose |
|---|---|---|
| customers | Customer | Customer information |
| orders | Order | Order and delivery lifecycle |
| order_items | Order item | Products purchased and seller/price details |
| order_payments | Payment | Payment information |
| order_reviews | Review | Customer ratings and review information |
| products | Product | Product attributes and categories |
| sellers | Seller | Seller information |
| geolocation | Geolocation record | Location information |
| product_category_name_translation | Category | Category name translation |

## Key Relationships

- customers -> orders : 1-to-many
- orders -> order_items : 1-to-many
- orders -> order_payments : 1-to-many
- orders -> order_reviews : 1-to-many (maybe)
- products -> order_items : 1-to-many
- sellers -> order_items : 1-to-many
- product_category_name_translation -> products : 1-to-many
- customer/seller ZIP prefix -> geolocation

## Keys

| Table | Primary Key | Foreign Keys |
|---|---|---|
| customers | customer_id | — |
| orders | order_id | customer_id |
| order_items | (order_id, order_item_id) | order_id, product_id, seller_id |
| order_payments | (order_id, payment_sequential) | order_id |
| order_reviews | review_id* | order_id |
| products | product_id | product_category_name |
| sellers | seller_id | seller_zip_code_prefix |
| geolocation | geolocation_zip_code_prefix* | — |
| category_translation | product_category_name | — |

## Data Grain

| Table | One row represents |
|---|---|
| customers | One customer record |
| orders | One order |
| order_items | One item within an order |
| order_payments | One payment record within an order |
| order_reviews | One review record |
| products | One product |
| sellers | One seller |
| geolocation | One geolocation record |
| category_translation | One category translation |

## Cardinality

The dataset contains several one-to-many relationships.

For example:

1 customer → many orders
1 order → many order items
1 order → many payment records
1 seller → many order items
1 product → many order items

Therefore, joins must be performed with careful consideration of the
resulting grain.

## Analytical Mapping

| Business Area | Main Tables |
|---|---|
| Sales / Revenue | orders, order_items |
| Customers | customers, orders, order_items |
| Products | products, order_items |
| Sellers | sellers, order_items |
| Payments | orders, order_payments |
| Delivery | orders |
| Reviews | orders, order_reviews |
| Geography | customers/sellers, geolocation |
| Categories | products, category_translation |