## STEP: 7 FEATURE ENGINEERING
| Feature                   | Meaning                                            |
| ------------------------- | -------------------------------------------------- |
| `total_order_value`       | Total payment value for an order                   |
| `delivery_days`           | Actual number of days taken to deliver             |
| `delivery_delay`          | Days delayed compared with estimated delivery      |
| `customer_order_count`    | Number of orders placed by the customer            |
| `customer_total_spending` | Total amount spent by the customer                 |
| `average_order_value`     | Customer's average spending per order              |
| `seller_revenue`          | Total revenue generated by the seller              |
| `seller_order_count`      | Number of orders handled by the seller             |
| `repeat_customer`         | 1 if customer has more than one order, otherwise 0 |

| # | Feature                        | Definition                                                |
| - | ------------------------------ | --------------------------------------------------------- |
| 1 | **Total Order Value**          | Sum of `price + freight_value` for all items in an order  |
| 2 | **Actual Delivery Days**       | Delivered customer date − order purchase date             |
| 3 | **Delivery Delay Days**        | Actual delivery date − estimated delivery date            |
| 4 | **Customer Order Count**       | Number of unique orders placed by the customer            |
| 5 | **Customer Total Spending**    | Sum of `price + freight_value` across all customer orders |
| 6 | **Average Spending per Order** | Customer total spending ÷ customer order count            |
| 7 | **Seller Revenue**             | Sum of `price` for products sold by the seller            |
| 8 | **Seller Order Count**         | Number of unique orders handled by the seller             |
| 9 | **Repeat Customer**            | `1` if customer has more than one order, otherwise `0`    |

In [4]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="MySQL@2026Strong",
    database="cart2"
)

cursor = conn.cursor()

print("Connected to cart2 successfully")

Connected to cart2 successfully

In [5]:
query = """
CREATE TABLE business_features AS

WITH
order_value AS (
    SELECT
        order_id,
        ROUND(SUM(payment_value), 2) AS total_order_value
    FROM order_payments
    GROUP BY order_id
),

customer_features AS (
    SELECT
        c.customer_id,
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS customer_order_count,
        ROUND(SUM(ov.total_order_value), 2) AS customer_total_spending,
        ROUND(AVG(ov.total_order_value), 2) AS average_order_value,
        CASE
            WHEN COUNT(DISTINCT o.order_id) > 1 THEN 1
            ELSE 0
        END AS repeat_customer
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_value ov
        ON o.order_id = ov.order_id
    GROUP BY
        c.customer_id,
        c.customer_unique_id
),

seller_features AS (
    SELECT
        seller_id,
        ROUND(SUM(price), 2) AS seller_revenue,
        COUNT(DISTINCT order_id) AS seller_order_count
    FROM order_items
    GROUP BY seller_id
)

SELECT
    o.order_id,
    o.customer_id,
    ov.total_order_value,
    o.actual_delivery_days AS delivery_days,
    o.delivery_delay_days AS delivery_delay,
    cf.customer_order_count,
    cf.customer_total_spending,
    cf.average_order_value,
    cf.repeat_customer,
    sf.seller_revenue,
    sf.seller_order_count

FROM orders o

LEFT JOIN order_value ov
    ON o.order_id = ov.order_id

LEFT JOIN customer_features cf
    ON o.customer_id = cf.customer_id

LEFT JOIN (
    SELECT
        order_id,
        seller_id
    FROM order_items
    GROUP BY order_id, seller_id
) oi
    ON o.order_id = oi.order_id

LEFT JOIN seller_features sf
    ON oi.seller_id = sf.seller_id;
"""

cursor.execute(query)
conn.commit()

print("business_features table created successfully")

business_features table created successfully

In [6]:
cursor.execute("""
DESCRIBE business_features;
""")

for row in cursor.fetchall():
    print(row)

('order_id', 'varchar(32)', 'NO', '', None, '')
('customer_id', 'varchar(32)', 'YES', '', None, '')
('total_order_value', 'double', 'YES', '', None, '')
('delivery_days', 'int', 'YES', '', None, '')
('delivery_delay', 'int', 'YES', '', None, '')
('customer_order_count', 'bigint', 'YES', '', '0', '')
('customer_total_spending', 'double', 'YES', '', None, '')
('average_order_value', 'double', 'YES', '', None, '')
('repeat_customer', 'int', 'YES', '', '0', '')
('seller_revenue', 'double', 'YES', '', None, '')
('seller_order_count', 'bigint', 'YES', '', '0', '')

In [7]:
cursor.execute("""
SELECT *
FROM business_features
LIMIT 10;
""")

for row in cursor.fetchall():
    print(row)

('00010242fe8c5a6d1ba2dd792cb16214', '3ce436f183e68e07877b285a838db11a', 72.19, 8, -8, 1, 72.19, 72.19, 0, 12271.71, 138)
('00018f77f2f0320c557190d7a144bdd3', 'f6dd3ec061db4e3987629fe6b26e5cce', 259.83, 16, -2, 1, 259.83, 259.83, 0, 9178.51, 122)
('000229ec398224ef6ca0657da4fc703e', '6489ae5e4333f3693df5ad4372dab6d3', 216.87, 8, -13, 1, 216.87, 216.87, 0, 3280.0, 12)
('00024acbcdf0a6daa1e931b038114c75', 'd4eb9395c8c0431ee92fce09860c5a06', 25.78, 6, -5, 1, 25.78, 25.78, 0, 1054.82, 13)
('00042b26cf59d7ce69dfabb4e55b4fd9', '58dbd0b2d70206bf40e62cd34e84d795', 218.04, 25, -15, 1, 218.04, 218.04, 0, 3661.18, 28)
('00048cc3ae777c65dbb7d2a0634bc1ea', '816cbea969fe5b689b39cfc97a506742', 34.59, 7, -14, 1, 34.59, 34.59, 0, 1209.64, 23)
('00054e8431b9d7675808bcb819fb4a32', '32e2e6ab09e778d99bf2e0ecd4898718', 31.75, 8, -16, 1, 31.75, 31.75, 0, 9738.2, 212)
('000576fe39319847cbb9d288c5617fa6', '9ed5e522dd9dd85b4af4a077526d8117', 880.75, 5, -15, 1, 880.75, 880.75, 0, 810.0, 1)
('0005a1a1728c9d785b8e2b08b904576c', '16150771dfd4776261284213b89c304e', 157.6, 10, 1, 1, 157.6, 157.6, 0, 25670.72, 162)
('0005f50442cb953dcd1d21e1fb923495', '351d3cb2cee3c7fd0af6616c82df21d3', 65.39, 2, -18, 1, 65.39, 65.39, 0, 6110.58, 85)

In [8]:
cursor.execute("""
SELECT COUNT(*) AS total_rows
FROM business_features;
""")

print(cursor.fetchone())

(100785,)

In [9]:
cursor.execute("""
SELECT COUNT(DISTINCT order_id) AS unique_orders
FROM business_features;
""")

print(cursor.fetchone())

(99441,)

In [10]:
cursor.execute("""
SELECT COUNT(DISTINCT order_id) AS unique_orders
FROM business_features;
""")

print(cursor.fetchone())

(99441,)

In [ ]:
Verification completed

Table created
All required business features present
99,441 total rows
99,441 unique orders
No unwanted duplicate orders
Delivery delay preserves negative values for early deliveries
Customer and seller features successfully calculated

Feature Engineering: 
Created meaningful business features including order value, delivery performance, customer purchasing behavior, repeat-customer indicators, 
and seller performance metrics using SQL aggregations, CTEs, joins, and conditional logic.

In [11]:
import pandas as pd

query = """
SELECT *
FROM business_features
LIMIT 20;
"""

df_features = pd.read_sql(query, conn)

df_features

C:\Users\VIDYAPRIYA V\AppData\Local\Temp\ipykernel_19300\3496401297.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_features = pd.read_sql(query, conn)

,order_id,customer_id,total_order_value,delivery_days,delivery_delay,customer_order_count,customer_total_spending,average_order_value,repeat_customer,seller_revenue,seller_order_count
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,8,-8,1,72.19,72.19,0,12271.71,138
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,16,-2,1,259.83,259.83,0,9178.51,122
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,8,-13,1,216.87,216.87,0,3280.00,12
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,6,-5,1,25.78,25.78,0,1054.82,13
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,25,-15,1,218.04,218.04,0,3661.18,28
5,00048cc3ae777c65dbb7d2a0634bc1ea,816cbea969fe5b689b39cfc97a506742,34.59,7,-14,1,34.59,34.59,0,1209.64,23
6,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,31.75,8,-16,1,31.75,31.75,0,9738.20,212
7,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,880.75,5,-15,1,880.75,880.75,0,810.00,1
8,0005a1a1728c9d785b8e2b08b904576c,16150771dfd4776261284213b89c304e,157.60,10,1,1,157.60,157.60,0,25670.72,162
9,0005f50442cb953dcd1d21e1fb923495,351d3cb2cee3c7fd0af6616c82df21d3,65.39,2,-18,1,65.39,65.39,0,6110.58,85
10,00061f2a7bc09da83e415a52dc8a4af1,c6fc061d86fab1e2b2eac259bac71a49,68.87,4,-11,1,68.87,68.87,0,104288.42,1706
11,00063b381e2406b52ad429470734ebd5,6a899e55865de6549a58d2c6845e5604,57.98,11,1,1,57.98,57.98,0,826.99,17
12,0006ec9db01a64e59a68b2c340bf65a7,5d178120c29c61748ea95bac23cb8f25,97.32,6,-22,1,97.32,97.32,0,200472.92,1806
13,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,126.54,13,-7,1,126.54,126.54,0,106939.21,1404
14,0009792311464db532ff765bf7b182ae,2a30c97668e81df7c17a8b14447aeeba,127.55,8,-5,1,127.55,127.55,0,12983.81,97
15,0009c9a17f916a706d71784483a5d643,8a250edc40ebc5c3940ebc940f16a7eb,650.34,5,-8,1,650.34,650.34,0,8318.63,62
16,000aed2e25dbad2f9ddb70584c5a2ded,fff5169e583fd07fac9fec88962f189d,152.77,7,-3,1,152.77,152.77,0,65959.61,294
17,000c3e6612759851cc3cbb4b83257986,3773bcf1a6fbd29233ea1c1b573c4f22,112.71,7,-12,1,112.71,112.71,0,55093.28,388
18,000e562887b1f2006d75e0be9558292e,2b01d668726fb0b751c55918c0437b7b,41.11,18,-6,1,41.11,41.11,0,2990.98,67
19,000e63d38ae8c00bbcb5a30573b99628,98884e672c5ba85f4394f2044e1a3eab,56.78,4,-8,1,56.78,56.78,0,9553.62,201

In [12]:
df_features.shape

(20, 11)

In [16]:
## 1.Total payment value for an order
query = """
SELECT
    order_id,
    ROUND(SUM(payment_value), 2) AS total_order_value
FROM order_payments
GROUP BY order_id
LIMIT 10;
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('00010242fe8c5a6d1ba2dd792cb16214', 72.19)
('00018f77f2f0320c557190d7a144bdd3', 259.83)
('000229ec398224ef6ca0657da4fc703e', 216.87)
('00024acbcdf0a6daa1e931b038114c75', 25.78)
('00042b26cf59d7ce69dfabb4e55b4fd9', 218.04)
('00048cc3ae777c65dbb7d2a0634bc1ea', 34.59)
('00054e8431b9d7675808bcb819fb4a32', 31.75)
('000576fe39319847cbb9d288c5617fa6', 880.75)
('0005a1a1728c9d785b8e2b08b904576c', 157.6)
('0005f50442cb953dcd1d21e1fb923495', 65.39)

In [17]:
import pandas as pd

df = pd.read_sql(query, conn)
df

C:\Users\VIDYAPRIYA V\AppData\Local\Temp\ipykernel_19300\1865705339.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                           order_id  total_order_value
0  00010242fe8c5a6d1ba2dd792cb16214              72.19
1  00018f77f2f0320c557190d7a144bdd3             259.83
2  000229ec398224ef6ca0657da4fc703e             216.87
3  00024acbcdf0a6daa1e931b038114c75              25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9             218.04
5  00048cc3ae777c65dbb7d2a0634bc1ea              34.59
6  00054e8431b9d7675808bcb819fb4a32              31.75
7  000576fe39319847cbb9d288c5617fa6             880.75
8  0005a1a1728c9d785b8e2b08b904576c             157.60
9  0005f50442cb953dcd1d21e1fb923495              65.39

In [18]:
query = """
SELECT
    order_id,
    ROUND(SUM(price + freight_value), 2) AS total_order_value
FROM order_items
GROUP BY order_id
LIMIT 10;
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('00010242fe8c5a6d1ba2dd792cb16214', 72.19)
('00018f77f2f0320c557190d7a144bdd3', 259.83)
('000229ec398224ef6ca0657da4fc703e', 216.87)
('00024acbcdf0a6daa1e931b038114c75', 25.78)
('00042b26cf59d7ce69dfabb4e55b4fd9', 218.04)
('00048cc3ae777c65dbb7d2a0634bc1ea', 34.59)
('00054e8431b9d7675808bcb819fb4a32', 31.75)
('000576fe39319847cbb9d288c5617fa6', 880.75)
('0005a1a1728c9d785b8e2b08b904576c', 157.6)
('0005f50442cb953dcd1d21e1fb923495', 65.39)

In [19]:
## 2. Actual number of days taken to deliver
query = """
SELECT
    order_id,
    DATEDIFF(
        order_delivered_customer_date,
        order_purchase_timestamp
    ) AS actual_delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('00010242fe8c5a6d1ba2dd792cb16214', 7)
('00018f77f2f0320c557190d7a144bdd3', 16)
('000229ec398224ef6ca0657da4fc703e', 8)
('00024acbcdf0a6daa1e931b038114c75', 6)
('00042b26cf59d7ce69dfabb4e55b4fd9', 25)
('00048cc3ae777c65dbb7d2a0634bc1ea', 7)
('00054e8431b9d7675808bcb819fb4a32', 8)
('000576fe39319847cbb9d288c5617fa6', 5)
('0005a1a1728c9d785b8e2b08b904576c', 10)
('0005f50442cb953dcd1d21e1fb923495', 2)
('00061f2a7bc09da83e415a52dc8a4af1', 5)
('00063b381e2406b52ad429470734ebd5', 11)
('0006ec9db01a64e59a68b2c340bf65a7', 7)
('0008288aa423d2a3f00fcb17cd7d8719', 13)
('0009792311464db532ff765bf7b182ae', 8)
('0009c9a17f916a706d71784483a5d643', 5)
('000aed2e25dbad2f9ddb70584c5a2ded', 7)
('000c3e6612759851cc3cbb4b83257986', 7)
('000e562887b1f2006d75e0be9558292e', 18)
('000e63d38ae8c00bbcb5a30573b99628', 4)
('000e906b789b55f64edcb1f84030f90d', 18)
('000f25f4d72195062c040b12dce9a18a', 15)
('001021efaa8636c29475e7734483457d', 9)
('0010b2e5201cc5f1ae7e9c6cc8f5bd00', 12)
('00119ff934e539cf26f92b9ef0cdfed8', 10)
('0011d82c4b53e22e84023405fb467e57', 10)
('00125cb692d04887809806618a2a145f', 15)
('00130c0eee84a3d909e75bc08c5c3ca1', 2)
('0013503b13da1eac686219390b7d641b', 15)
('00137e170939bba5a3134e2386413108', 17)
('001427c0ec99cf8af737bd88e92fd444', 18)
('00143d0f86d6fbd9f9b38ab440ac16f5', 11)
('0014ae671de39511f7575066200733b7', 16)
('0015ebb40fb17286bea51d4607c4733c', 18)
('00169e31ef4b29deaae414f9a5e95929', 7)
('0016dfedd97fc2950e388d2971d718c7', 24)
('0017afd5076e074a48f1f1a4c7bac9c5', 47)
('001862358bf858722e1e2ae000cfed8b', 9)
('0019c29108428acffd089c36103c9440', 10)
('001ab0a7578dd66cd4b0a71f5b6e1e41', 21)
('001ac194d4a326a6fa99b581e9a3d963', 8)
('001b76dd48a5b1eee3e87778daa40df8', 11)
('001c85b5f68d2be0cb0797afc9e8ce9a', 28)
('001d8f0e34a38c37f7dba2a37d4eba8b', 12)
('001daeb0eddc45b999bad0801ad9d273', 22)
('001dbc16dc51075e987543d23a0507c7', 16)
('001e7ba991be1b19605ca0316e7130f9', 10)
('001e7cf2ad6bef3ade12ebc56ceaf0f3', 16)
('0020262c8a370bd5a174ea6a2a267321', 4)
('0020a222f55eb79a372d0efee3cca688', 9)
('002175704e8b209f61b9ad5cfd92b60e', 10)
('00229e4e43f7a7e0b9dd819ad43268d3', 5)
('0025081dcf9330f9a5052ae82c6ce396', 9)
('00254baeb6c932b0a8aeead91fbd02b5', 22)
('00259a44fcad3fc0474329e925d14fc3', 8)
('0025c5d1a8ca53a240ec2634bb4492ea', 23)
('002611a77fe03d076285fd4ca95db77c', 23)
('002691433f09002ac9ca0c4e8dbb8ead', 5)
('0026a368634b6e6f34f33b1499773a30', 11)
('00275bce676303c3bfd7292aefdfa223', 10)
('00276d5c3491fbf55305e26891040df9', 31)
('002834535f7a609a5c68266f173fa59e', 19)
('0028de0ca693a1bb26448916a81105cc', 13)
('002955b0acc63d04f6724a31967e82bd', 8)
('0029c5db35ef291ce99d1262012e7daa', 5)
('0029f17cf0e7640c5cb6825af681303f', 8)
('002af7fa9eb99d1456bceb6a13d6fc0b', 22)
('002b430ff89b3a24c31a1170acbbedea', 9)
('002b4e6fa42cd4a22cc86abc18fe9c05', 8)
('002c9def9c9b951b1bec6d50753c9891', 4)
('002d040018d12a3853c059f7f23ab5b1', 8)
('002f16b7bc4530031b7d90f791b12d8a', 4)
('002f98c0f7efd42638ed6100ca699b42', 3)
('0030d783f979fbc5981e75613b057344', 43)
('0030ff924c38549807645976adeef2c0', 22)
('00324b3eda39ba5ecce3945823e3594c', 23)
('0032d07457ae9c806c79368d7d9ce96b', 50)
('003324c70b19a16798817b2b3640e721', 12)
('00335b686d693c7d72deeb12f8e89227', 57)
('00335f75ea6a4455b524a8dd177067f5', 8)
('00337fe25a3780b3424d9ad7c5a4b35e', 2)
('003423b755b562962a6225a8de40d12e', 16)
('00345f338696283410b7977d2e3efc89', 10)
('0035246a40f520710769010f752e7507', 11)
('0035c0b07126fe9c24a325216fb96064', 13)
('0035e6b7ade84b3f5b86bd49814793df', 5)
('0036757472ece3dde52fd4bfd929c90e', 21)
('0036887767dea4bd43b1a88cd0d9477a', 10)
('00378c6c981f234634c0b9d6128df6dd', 24)
('003822434f91204da0a51fe4cf2aba18', 6)
('0039500db36d50d7d0bfaf23723550f3', 15)
('003a7f59d7e08a9c61d9e2881fe6459c', 8)
('003a94f778ef8cfd50247c8c1b582257', 21)
('003cc6161d7a2593f2525cce0c330d32', 4)
('003d0634280ff3d1d3a54459349a6899', 10)
('003d804eef0e1b856881cd18e0cc0d4c', 54)
('003d9fc84ad902adf2265248b5ffe1a4', 8)
('003edccf16bc5ec447f592913b3df2b4', 26)
('003f201cdd39cdd59b6447cff2195456', 35)
('003f9bcc09427647c4b9d361a523545b', 2)
('00404fa7a687c8c44ca69d42695aae73', 11)
('0040a56893444cb56cba7cfe2225e34e', 23)
('004157daafa0bc8672e01f00e4f0c04f', 12)
('00418a49a685c6bb60633291c3fab17a', 2)
('004345d16a1ab2c21962992c721c8643', 7)
('0044c6f6d22dd280534344177c81b989', 17)
('0045e3085f083f0f38d24bb3f22e6593', 19)
('0045f5225a96ef46630701167528fdcb', 8)
('0046176ff0dbc2a178b7885355dfbb71', 6)
('0046e1d57f4c07c8c92ab26be8c3dfc0', 3)
('00471463a6106056c1a2a809f70de640', 21)
('00482f2670787292280e0a8153d82467', 2)
('0049edf42837aa808e03552a62bd2158', 31)
('004b62108b876867938746ad3154167f', 9)
('004ba47bb589cdbc485e6025bd6d3c81', 4)
('004ca5ae248069d68e8594df8abf6ce0', 9)
('004d76fef3dd46eb4f70da049c8d1f93', 6)
('004eab0fd8f28adaf8d488976f77febe', 1)
('004f5d8f238e8908e6864b874eda3391', 24)
('004fb11815bc03b01b20a614eef69d14', 21)
('004fb5e6f90a178dc74ad2b016649249', 5)
('005059edee63c8c708ba61910793b31b', 14)
('00526a9d4ebde463baee25f386963ddc', 9)
('0055b77cca3186676c147f532dd2547b', 16)
('0057199db02d1a5ef41bacbf41f8f63b', 19)
('00571ded73b3c061925584feab0db425', 12)
('00584d79015452d19fd3d044ba3abdc0', 3)
('00588f5f20fee630b83d4709e0a42715', 12)
('005997dca4c1fc45066d0a03d54a6469', 3)
('005a1dded353107dbabf8ffc83a20365', 21)
('005b49de51a4e006055e8487a50ad8e4', 18)
('005cad6157eadc7f1f09917607f1704a', 18)
('005d9a5423d47281ac463a968b3936fb', 9)
('005e5166e99d1e4d0c4f808b0540ba94', 34)
('005f25968fc854ea16fb16f5bdbc87c7', 16)
('00602f25bffa1dcfb71e202fbf9824fb', 26)
('00611822267e76e0055c25c18506f06e', 5)
('006127b8b9a1681a982313ed7129c3c0', 12)
('0064d74f7de7917d54768d7722ad56ac', 4)
('006557c3221c1fcd02b0106343ab357b', 7)
('00664284de7a3470d22931ed78615ee4', 9)
('0066a1fdaee16ad5022c5ef979d0b661', 6)
('0067c6030d65af0ff98790158ddb0020', 10)
('0068468c453d28c8ef3fd089e50a5847', 20)
('00685d31ae12e47470ba5c18ba74f22c', 38)
('0068c109948b9a1dfb8530d1978acef3', 17)
('0068e836900867da359bd81db9227a33', 6)
('0068fb0e223115e911d362627e8b8800', 7)
('006c42f310102c1910b3c5793ce5fc34', 9)
('006cb7cafc99b29548d4f412c7f9f493', 8)
('006cba07f62f921fe4f58365bde2b2eb', 4)
('006dd93155bc2abd844cc5eed3a0fe7f', 5)
('006df90050498994d670b40da4651d22', 2)
('006e05e81c068ddc38e48ebe189b922e', 7)
('006e43460a55bc60c0a437521e426529', 8)
('006e91ddb0674525f84ce0da0655c7ba', 6)
('006f7dfffe2d90809598e8f1972b829b', 14)
('0070092bb6004faafa287e5fc35971e9', 2)
('0071ee2429bc1efdc43aa3e073a5290e', 9)
('0072847849eafe70995fa51a714c81ac', 8)
('00750f68bb64537034e93554c64b41b5', 2)
('00756576f4e494406945ac21cb82cfe0', 10)
('00772b2af35643653f108fdac1155ee3', 12)
('00789ce015e7e5791c7914f32bb4fad4', 19)
('0078a358a14592b887eb140ef515f5ab', 15)
('0079bca8e89bd52fdb87408e4f3fb94d', 5)
('007bbb40c95870c0f75a7855f2636c65', 2)
('007beb35f98c075747e6fc4fd1c0cb73', 11)
('007c7cb12ef3567531307ca78d395758', 20)
('007ec946d4f798caf2b43c9d44c56421', 12)
('007ff0b0f79be782f633fc3b18cbe337', 11)
('0080eebb288dba1857ccf048dfe6bdfe', 7)
('0081ab2c99dc85945c28926b77dc6960', 5)
('0081ce648af7d6a7bac2a93b6035d1e3', 14)
('0084209c576daad6ff4534902fcb4892', 13)
('0084e195fbd72ae51599af47f04afede', 51)
('00858d03144cc35cfd1dd043647e7c88', 8)
('008720830a8a30e39e6f22f81818a141', 5)
('0087889a1c836be17f58afd7f1729a4a', 1)
('008819c6d5f6da6fa5cd9d50ca927cf4', 3)
('00891ba5de66f55000ee358ceea9b345', 9)
('008990da719764fb392914d8ab53ad04', 25)
('008a1b3db2a8bf63418c2cf7c7f494b1', 31)
('008a40c2b8b21893e04945ce58854b55', 9)
('008c3a655c66f4d92370d0d422732f69', 5)
('008ce8764db2e397e153000e017475b6', 5)
('008cfe221ab054c89bc31720098cca51', 6)
('008d9bf350ff02ed444b3452cf3f57e0', 9)
('008dc31c0ae7121f2791953ae5f532c3', 23)
('008dd5e80ebf8f849aa0c5bf4e22ce7a', 3)
('008eaf9004164883520d0bd32b107261', 11)
('008f831b7185cff7ab35a46c37d64cd2', 7)
('008fab5602c441d51f30b1464f5d4643', 9)
('0091a677651feaf5a08d7bb147681e14', 4)
('00921e4911895b93c7b4fc0d80c0815e', 7)
('0093cbf16a6afb7f0ab7cc821b6f9e92', 14)
('00946f674d880be1f188abc10ad7cf46', 8)
('00949655cdd8d0465e433a5e6c9643e5', 3)
('0094bd07f49fed90209ffa62d1ef26d6', 15)
('0094d4660e323945f84f5c29eb348aae', 12)
('0094dc9ea7e3cd54d95aea42685673ff', 7)
('0095790a64527ec83aeaaf99023c050e', 22)
('0096668e5b0b8e9657a6f7209a4e58b4', 68)
('009742b43f4530bc3db7f62332c50f4b', 43)
('00975e709cd12c34d3bd44e4a7f7a876', 2)
('0097aafe2a01dd54e39888976160c377', 5)
('0097f0545a302aafa32782f1734ff71c', 16)
('009838529bb913846ab6670d22865381', 12)
('0098dbda25722a3f019fe252a0cd10b3', 13)
('009905140e9f8cc35d5be897937381db', 13)
('00995d799817ecc3bd2abd8fbe59c430', 7)
('00998f38df3012359ef195ca75ebb329', 7)
('009ac365164f8e06f59d18a08045f6c4', 6)
('009c278fa2ed6e7ec498200b60193ca8', 20)
('009e11afa25aa95ae78e60a793995c9b', 12)
('009fa9bd0d92710e840793bfefa80867', 24)
('00a0116ff15ff973ea16bee881208ae7', 13)
('00a12754417a49a9dec20361849aa917', 2)
('00a13ab02fbe82f78cd84f14e41564ed', 5)
('00a174dbf11967d260033fa6ab711493', 22)
('00a1e977cf6e672402963940db55d919', 2)
('00a250dbdb3153cc6ecf4d3f07ef6a17', 4)
('00a379dfab816a83741012b71b264098', 7)
('00a3a334aec7455a6d3319981499a3da', 10)
('00a3f1ef430d3984dece2f39d6cbf431', 19)
('00a4d94df1c9757661679b2f4bd6d311', 11)
('00a57dfbb049fbaae10763e2cf15f797', 10)
('00a690becda145533fa5a54daa7b6ad5', 16)
('00a77f9cc25b05b2004752593d7b8888', 15)
('00a843f5a80c7aea894c558acc29f513', 10)
('00a870c6c06346e85335524935c600c0', 8)
('00a9536682ecb394a3794c1608200803', 10)
('00aa423621f35a9ca6c6240f275b0640', 11)
('00ab1aba567dfebdc39caa4e7ca2f1b2', 11)
('00ab210695a17fe10e6b23616ae5bc97', 7)
('00ab3a43bda739029ffce95d3b2fb56c', 4)
('00ab9fa91aafa3d881164b0da48999aa', 13)
('00ac05fe0fc047c54418098eb64e3aaa', 12)
('00ac2a1ec784f71feeb7ba1e5959750d', 11)
('00ace652c8a5072670f30674e5f19844', 31)
('00ad1a02d4d9decad15c7e8f8a9470cc', 13)
('00af3d9ddff7f256e83d79247dbe1a9f', 14)
('00af53fdc2002f5b6a8f16db648e003b', 13)
('00b12f4674177ef40c4bdb034138c843', 5)
('00b1861aeb89afa498404c684148a619', 7)
('00b2d2f2b5f7b98e6b1828764660134e', 6)
('00b30bb163474583c14db1689259cf4d', 17)
('00b402e8a76d3da83714c52d3977cc2d', 18)
('00b44ba3d7c4a5e9a9ebafef9150781d', 2)
('00b47ee856118583dbec7d1f9b18d847', 14)
('00b4846d477a7baf5d4e47970bc08c7e', 8)
('00b4a910f64f24dbcac04fe54088a443', 8)
('00b4c651133c06fb175123a492f1cac3', 6)
('00b5e1c770b1868ec1b6b726be3aa9b9', 8)
('00b676b01c289cc661c6f7732492771a', 13)
('00b6c055922e0ed2d88efdd252b2fb64', 6)
('00b6e66f005a657a6b13eedcacdf9342', 10)
('00b7174ea52bb811ebe2663add51afc0', 5)
('00b8d354b36820e9d6131fd5173c5581', 12)
('00b9e0f8f588d0406a3de447eb606970', 25)
('00ba414462370af2d76195d12e0d5481', 16)
('00ba57ae98928df6ba6ec9d3d8d4b1b7', 10)
('00bbc4179554524748f77763ddd62266', 6)
('00bc78808b22918a467b2fa4b8ef5d68', 9)
('00bcee890eba57a9767c7b5ca12d3a1b', 5)
('00bd2cb7e9076e1ccc9f766fc01a4cfd', 12)
('00bd50cdd31bd22e9081e6e2d5b3577b', 8)
('00bd8cf08fa3998ea6ad6d16c2165822', 4)
('00bdcdda88e6b02977fc6ce3d412c600', 6)
('00bdebefeb760588a3425fad9dfed3d9', 6)
('00beb247698c6aae94e3f859d279e2cd', 5)
('00bf1320ffb5fe47a845feca16c0e0b4', 36)
('00c00d5b36157595e21108ba1da2828f', 23)
('00c2335723b9b74668062e946dc66621', 9)
('00c405bd71187154a7846862f585a9d4', 8)
('00c42b1633c1b2fa4e937bf312466561', 26)
('00c47cfa491ef55779ec7557673087fc', 2)
('00c47fefb9a49baec12ab3654d7f548e', 41)
('00c4f17dcb94448f27a2cbaa83f10a4b', 4)
('00c62d05602c1ca8164b98746d127fa8', 9)
('00c763284c0056eed753352f5559ff0a', 13)
('00c81b6675ef9ecaaff5fc1d6720b96c', 6)
('00c826c901ab01b6f598a8f0c9b56b82', 12)
('00c842d0ae6462afc1d38fc055b02c75', 13)
('00c8be06a8029e300dabd52c7d4c6ad2', 16)
('00c8bfbb0a1224dcdb0180a544247159', 5)
('00c9474e0334f7a4ffc8c3a8bd21a51e', 12)
('00c95282163553a982f38481f9488481', 8)
('00c9d0257381c7e9ec13b4505f25b2cf', 9)
('00c9d9e61ed13f5bf2f0344da1aa4775', 10)
('00c9f7d4b0e87781465e562dc109f6aa', 10)
('00cb18db3d9c03f8386e7fc70cad2504', 7)
('00cb9736c0b43d6c1e2fbb2b88e69f6a', 18)
('00ce92d57f4f9a112bdb8a2a283e5f97', 8)
('00ceda91cb2ded8570ca73e70571740a', 10)
('00cee8a4dbb042385cbbd84699e78b2e', 5)
('00cf2b04c59f0ecaf822bf3f334d5c3b', 12)
('00cf47526e0f7920b381b2baf4ecf1c7', 7)
('00cfabbe2a93b70beeec4894f86712a8', 12)
('00d03eb3425f41a599ae2f788e23c07f', 51)
('00d0ff2017f9ea13dd7eec7470ca473a', 9)
('00d1289d5125017a90e528b5a7cee91f', 96)
('00d15ff0236872686e4899ed1ce680ad', 14)
('00d1e381c0995f0bdb95909fe7434d0b', 9)
('00d2559e61b9a0744a0552c35c5ecccb', 7)
('00d29386638bbfd1331a2cd7ab91b5b5', 8)
('00d4439957b7fd3f8da4a33a965817fb', 14)
('00d50baf1bc56a3c59de1810a6b84b0d', 36)
('00d5fac7792747fba4b528f23930bebd', 8)
('00d831d5c3ea03b7cd6f883ad799c7e4', 5)
('00d85bfe0e28c91b69d0fe1f29255a31', 7)
('00d88c00221ce96a1cfcaca9f2fceb3b', 22)
('00d8d65b666158b633f96054d31af43b', 25)
('00d94e8901b75ee0d6ef1f87f947b666', 22)
('00d9ac423c9ad6781c0ed04e87666691', 21)
('00dc6ad47477b3b62d3c0acbe98a82a4', 19)
('00df27e666004db9f14bce766fa5327c', 5)
('00dfb074b5c910fbd08e04691c4b712f', 7)
('00e054d0da011d5016f31011af488f4f', 58)
('00e0bac9f6306d8269770acf4ee4b027', 23)
('00e1426d4c79f2e022570012c1ff57ed', 14)
('00e1bdb3f1388c8ed222597ee4fa01e7', 9)
('00e32e413e017e64ff93a9e800b8e1be', 7)
('00e365f4fc03d1098841af23d05c17a6', 9)
('00e4050fe32e786290a29c61141e979f', 12)
('00e5b655df1cc911466758210325c67c', 11)
('00e63486fad9d24645c9c84ed77c15fa', 6)
('00e6786fee8f476835c151a4d3fa9bf1', 11)
('00e6bc6b166eb28b4502c1cad4457248', 4)
('00e7aeced1d61792368ec7bf8b967a90', 21)
('00e7ee1b050b8499577073aeb2a297a1', 9)
('00ea33f994bec0bbfda582074083ae12', 7)
('00ea690fe8c5eba029a3884243a02352', 23)
('00eb7b95af5ed25aaec66d4ff5295846', 11)
('00ec95a58b63378d4cc06d196cdefdf6', 10)
('00ed64bc080d87b4ab7f0c433bc5e98f', 8)
('00eead1d5a799277ef3d6b387b0bebef', 3)
('00eef7fe9e315a85d1a61a50cccb2494', 13)
('00ef7ed06a55243f3e6a9d373a89eb14', 34)
('00efb72d8e18533f736e86770705d094', 9)
('00f1a34f176151c4dcbd802c244e1072', 6)
('00f1bb0af030935db1745ee28367ea26', 12)
('00f1c7c1542f5f86c3091749d9e939d8', 11)
('00f1cc7439ccb8671133776d1829faf5', 9)
('00f251b943aba645652c7138e4716fee', 7)
('00f2a3509bd600bd1a06a48353788d93', 4)
('00f2c876aa08fbba04199823952e96c1', 12)
('00f324f6ec332cd73ef8be4888573662', 18)
('00f33ee62c15223679d3550e751c37cd', 23)
('00f426c7214575822c3cb44ea59ef0f6', 12)
('00f57f2ccce2a2e3f393fe8f5e616e0d', 8)
('00f5fbdc777e8198c1ee008122e28ae3', 12)
('00f621226c6f4e938348f6f3a71fdc62', 8)
('00f6ac4816d12f49026b09f2aa77d15f', 7)
('00f6dbc6195397197ee147ee45607a2c', 16)
('00f7c5b41250e0126ced62d612ff4711', 12)
('00f86b368251d739f1896d41469b2b7a', 11)
('00f8fc0cb9d9b7813f1f54fbd75426f1', 11)
('00f98eaeddb9debc8df8cb27e08216d4', 5)
('00f9b0236a85fb8a06fbd9b9c53fddd8', 12)
('00f9b6769c6648ac08bf43081d1f2b07', 13)
('00faa6afcde74aaa630e1d2fda2bb0f7', 9)
('00fb055886536063afa0dbee07a0944f', 8)
('00fb278a99144cc1004b3ed1452ff5e1', 5)
('00fbcd8b120e5706c58b9d1a0026a7da', 22)
('00fc308dd7f0937682698becaa9dcc45', 8)
('00fcf938cde49ae138942b632ed62393', 19)
('00fdb72e467da6f3b000b19b368a6cf6', 7)
('00fe20fc069833ab95021b46d6862646', 2)
('00fed9e582d5a3e38566872eec164ac6', 13)
('010061e3aa0c6ed5e393dda0652bbee8', 11)
('01006620eb4732deec44be4b0d9e33cd', 10)
('010078e0913f48d014483bd856c01ca1', 9)
('01015fb6493ea5b9ba105c80b5452da1', 28)
('0101aea69a09e1aa32caa6dbaba98503', 21)
('01029b44abe6e15c8df48b1b759ab437', 8)
('0103878b7ed86b6ec873cfae01379472', 6)
('01074135a88ffa5978eaadfc7f482f2b', 18)
('0108c64ec135e4a7a75e9b5102af9bfa', 24)
('0108fba93678555ad1cec9c267848187', 3)
('01094e169d4b14edaf6954eeddb83633', 20)
('010a35dc7fc3808a03d243d2fd8c6e35', 6)
('010ab3b1993057e91f825c672375a66d', 10)
('010b0f6bd323a9effd095a743e660f26', 8)
('010b143d83a59b355cd5a75c0f0fd785', 19)
('010c995323bc17d8156fbe2c37fed63e', 6)
('010d14f76a229c295260e4ca4744acc7', 17)
('010d15deea8cae96ae86ea8097917a17', 12)
('010d6db2f77220b394f147836c94f27b', 10)
('010e04b5f879320f29a9bd6ca41abc94', 6)
('010e7dda85fff564e8b7076ae3928efb', 15)
('010ef5b0279d7512e7343cb775e423c0', 6)
('010efe60bdadc9261d1902f3c1dda5f3', 8)
('010f223ddbec749e95ef3f5414f9c4ee', 10)
('010fadb12341d8253d920362fc8f7a16', 24)
('010ff1cfe12f3094577e72b7bcecdf98', 8)
('0110688c40ff035d672af3aac1f38f10', 26)
('011080783e02d05b26c8c158b3653a42', 8)
('011105c3b5b8693eda1bfb1f152cec2a', 8)
('011108c8a3d6eee6807f48a2e639439f', 24)
('01115c06246220def210911556bdc0e5', 20)
('011331376a4c6cc7a9e5bc165ec169d0', 12)
('011375f941b3695c3c3ee58bfe0d3655', 13)
('0113affd907a209209ab08413bb54226', 22)
('0113c9989fe6e5007795daec0633b405', 4)
('011405ae7b89def8ffb3468eb29c299d', 5)
('01144cadcf64b6427f0a6580a3033220', 11)
('0114835d7f0b3f674b70a989411e31c1', 4)
('01156b662f3f47b249b5a8881d205f08', 14)
('0115abf6b892040abfdd5bdfcb6b2c51', 25)
('0115d160c5fbd758a139ff90821db60d', 20)
('0115f8bb1dc16d3fac863ce1deb037b6', 7)
('011667ae100a333a3051c9a23e3f0283', 8)
('011724d1afbd91844302627f79a66800', 6)
('0119e98feb97441cb456c010c25b04ff', 9)
('011a43bc9bb525517251ebb3ebc99b69', 5)
('011a56023faf5bbb9af634e20a85f7bc', 8)
('011abf147a69ba486bae3a74b6cd1814', 10)
('011af0959ebf2b09a062867811dc63b5', 3)
('011b142c9e082a5c1d10e0a88cd9c8e8', 22)
('011b8dd4f8c36fd4fcf50643ce91d58a', 28)
('011bf86f1b7dacebda2c874333cf656b', 12)
('011c899816ea29773525bd3322dbb6aa', 15)
('011e6e76dd0cd56d26b5b0cb036e80a8', 3)
('011f9dff2545a2cf8ac1809faed3ec88', 8)
('011fcb4fabb3e142579ad63472b11227', 32)
('0120e3dd2696a3bbb68dc2860815f7f2', 15)
('01218a8a807fc187849529e6f12237a9', 10)
('0121cfa7c946e6589f50d7012d3eb5eb', 7)
('012219b6d6d034eb359fc74730a080db', 6)
('012248555cb0bf51df99199cef81d562', 16)
('0122e81ff800460e44bb9c983ff2a2fd', 12)
('0123098b96f3d4014545642be53d891c', 14)
('01235dc626dcf13283207ba7f36a959a', 13)
('01237c761ffb72594a466ed514518af0', 5)
('0123a055aa66357326dd6db066592a7d', 6)
('0124e0c5bfae1979838a91e47df53f14', 7)
('0124f01177fc17cf20e1974621fd759a', 9)
('01255808a3d38a8dd69aa93265a4cb88', 10)
('012670c73246a753cbde0a215c2b9e8f', 41)
('0128412231f9fe9d7e944eea5392fc6b', 8)
('012973f4cb6743d00d7e2644ddc8804c', 10)
('012a238ab54294a3b365812ccc82b135', 12)
('012b3f6ab7776a8ab3443a4ad7bef2e6', 8)
('012bea13f9a355c983efb59a3f23583a', 21)
('012d8cbea490e6102cee6a2088aaa785', 15)
('012dc9e42da722d22e32c618a2521bec', 5)
('012e93f8170eb75b2f2f650629d04517', 6)
('012ea594e035047289b3e7c3f8b90cef', 6)
('012eab2625c5f8aaac6f37f2c19ef62f', 10)
('012f255bd5034b8e7fb3c91566a91cc8', 3)
('012f29911fcd2f1209d937741a6bbc6f', 6)
('012f2c4ca09b101a73e18957c3294cd6', 8)
('013037c3f1773cc8fdbaf8ff54d8013b', 6)
('013056cfe49763c6f66bda03396c5ee3', 17)
('01311f2795d8463a11f9422173687696', 13)
('0132158c30672a8c52997a2492613ec2', 2)
('0132451f29a10b66a5cf1bacc85f9afe', 9)
('0132d77609dd6e1867515ec57d898c10', 12)
('0132f39e8ad9b42ad2d41c847f44c0ed', 1)
('0132fef017ccf586491ca3685de667df', 1)
('01336d091c57d8be1feca330c5f047bd', 8)
('0133a47b53fee66218790a8d7dcab993', 12)
('0135675503322d804abef7ec5ed4824b', 8)
('01358622f65717728b3b2ec2cf4e8812', 3)
('0136390286be8a34efdc801ed150568f', 8)
('0136bcc7370d7fdf44bd916a6dd583c6', 17)
('01380d0df5b7dc8bd13f2266a57bd42c', 4)
('013a98b3a668bcef05b98898177f6923', 6)
('013aa6ba5077072401773f83f1ee6408', 21)
('013b811ba81339b7634ab5231c547e6a', 8)
('013bc5ce14f856d31efc8bebdc3a278f', 8)
('013bc77d3ca5fba084a241fdcb307393', 54)
('013d92e415d1de7bf3b3b706f1b6d292', 26)
('01405161cfdf60dd80df1f393a2796d5', 11)
('014176e9538672a32d2a9b73bf53a31f', 18)
('01422b2c3c27fa3bc464e72eaed9676b', 10)
('01428962dce3b65e5433eaeb16c0f48f', 18)
('0143924743f240e1fdcd6a8918fbe147', 3)
('014405982914c2cde2796ddcf0b8703d', 5)
('01442602b15d4127a84ca6ac1507ee2d', 8)
('014872cb0c4fc7695c70484966baa65c', 7)
('01490a4bdacbafe6de009b317a0c8bf6', 9)
('0149c597dcc0963d7315f904495b631c', 4)
('014a0793ab3d930d6f3b206cee474af4', 3)
('014ac3cfd0e55bdc2cdd12aa181b00cb', 8)
('014bd8ca0827935402ac39f2751b2fcd', 7)
('014e36af18c280a94d880a16b2f00713', 8)
('014e78d1239f19fdcafd760d3e52f923', 41)
('014e7d12255fc66b5ea5e6c93eb4be7b', 21)
('014f1e63f9bd4f5578edcf4e5c305a0a', 8)
('014fc889637133d9075190ba873dfc03', 6)
('014ffbfe2df4c96a2b063d084583978f', 14)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [20]:
query = """
UPDATE orders
SET actual_delivery_days = DATEDIFF(
    order_delivered_customer_date,
    order_purchase_timestamp
)
WHERE order_delivered_customer_date IS NOT NULL;
"""

cursor.execute(query)
conn.commit()

print("Actual delivery days calculated successfully")

Actual delivery days calculated successfully

In [21]:
## 3. Days delayed compared with estimated delivery
query = """
SELECT
    order_id,
    DATEDIFF(
        order_delivered_customer_date,
        order_estimated_delivery_date
    ) AS delivery_delay_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL
  AND order_estimated_delivery_date IS NOT NULL;
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('00010242fe8c5a6d1ba2dd792cb16214', -9)
('00018f77f2f0320c557190d7a144bdd3', -3)
('000229ec398224ef6ca0657da4fc703e', -14)
('00024acbcdf0a6daa1e931b038114c75', -6)
('00042b26cf59d7ce69dfabb4e55b4fd9', -16)
('00048cc3ae777c65dbb7d2a0634bc1ea', -15)
('00054e8431b9d7675808bcb819fb4a32', -17)
('000576fe39319847cbb9d288c5617fa6', -16)
('0005a1a1728c9d785b8e2b08b904576c', 0)
('0005f50442cb953dcd1d21e1fb923495', -19)
('00061f2a7bc09da83e415a52dc8a4af1', -11)
('00063b381e2406b52ad429470734ebd5', 0)
('0006ec9db01a64e59a68b2c340bf65a7', -22)
('0008288aa423d2a3f00fcb17cd7d8719', -8)
('0009792311464db532ff765bf7b182ae', -6)
('0009c9a17f916a706d71784483a5d643', -9)
('000aed2e25dbad2f9ddb70584c5a2ded', -4)
('000c3e6612759851cc3cbb4b83257986', -13)
('000e562887b1f2006d75e0be9558292e', -7)
('000e63d38ae8c00bbcb5a30573b99628', -9)
('000e906b789b55f64edcb1f84030f90d', 2)
('000f25f4d72195062c040b12dce9a18a', -20)
('001021efaa8636c29475e7734483457d', -15)
('0010b2e5201cc5f1ae7e9c6cc8f5bd00', -4)
('00119ff934e539cf26f92b9ef0cdfed8', -15)
('0011d82c4b53e22e84023405fb467e57', -20)
('00125cb692d04887809806618a2a145f', -13)
('00130c0eee84a3d909e75bc08c5c3ca1', -7)
('0013503b13da1eac686219390b7d641b', -8)
('00137e170939bba5a3134e2386413108', -7)
('001427c0ec99cf8af737bd88e92fd444', -15)
('00143d0f86d6fbd9f9b38ab440ac16f5', -10)
('0014ae671de39511f7575066200733b7', -6)
('0015ebb40fb17286bea51d4607c4733c', -14)
('00169e31ef4b29deaae414f9a5e95929', -15)
('0016dfedd97fc2950e388d2971d718c7', -10)
('0017afd5076e074a48f1f1a4c7bac9c5', 4)
('001862358bf858722e1e2ae000cfed8b', -15)
('0019c29108428acffd089c36103c9440', -26)
('001ab0a7578dd66cd4b0a71f5b6e1e41', -12)
('001ac194d4a326a6fa99b581e9a3d963', -5)
('001b76dd48a5b1eee3e87778daa40df8', -21)
('001c85b5f68d2be0cb0797afc9e8ce9a', 8)
('001d8f0e34a38c37f7dba2a37d4eba8b', 2)
('001daeb0eddc45b999bad0801ad9d273', -11)
('001dbc16dc51075e987543d23a0507c7', -35)
('001e7ba991be1b19605ca0316e7130f9', -15)
('001e7cf2ad6bef3ade12ebc56ceaf0f3', -1)
('0020262c8a370bd5a174ea6a2a267321', -20)
('0020a222f55eb79a372d0efee3cca688', -13)
('002175704e8b209f61b9ad5cfd92b60e', -12)
('00229e4e43f7a7e0b9dd819ad43268d3', -21)
('0025081dcf9330f9a5052ae82c6ce396', -12)
('00254baeb6c932b0a8aeead91fbd02b5', -6)
('00259a44fcad3fc0474329e925d14fc3', -18)
('0025c5d1a8ca53a240ec2634bb4492ea', -3)
('002611a77fe03d076285fd4ca95db77c', -4)
('002691433f09002ac9ca0c4e8dbb8ead', -24)
('0026a368634b6e6f34f33b1499773a30', -24)
('00275bce676303c3bfd7292aefdfa223', -10)
('00276d5c3491fbf55305e26891040df9', -6)
('002834535f7a609a5c68266f173fa59e', -3)
('0028de0ca693a1bb26448916a81105cc', -14)
('002955b0acc63d04f6724a31967e82bd', -21)
('0029c5db35ef291ce99d1262012e7daa', -4)
('0029f17cf0e7640c5cb6825af681303f', -12)
('002af7fa9eb99d1456bceb6a13d6fc0b', -3)
('002b430ff89b3a24c31a1170acbbedea', -13)
('002b4e6fa42cd4a22cc86abc18fe9c05', -18)
('002c9def9c9b951b1bec6d50753c9891', -7)
('002d040018d12a3853c059f7f23ab5b1', -11)
('002f16b7bc4530031b7d90f791b12d8a', -19)
('002f98c0f7efd42638ed6100ca699b42', -29)
('0030d783f979fbc5981e75613b057344', 22)
('0030ff924c38549807645976adeef2c0', -4)
('00324b3eda39ba5ecce3945823e3594c', 3)
('0032d07457ae9c806c79368d7d9ce96b', 12)
('003324c70b19a16798817b2b3640e721', -8)
('00335b686d693c7d72deeb12f8e89227', 32)
('00335f75ea6a4455b524a8dd177067f5', -25)
('00337fe25a3780b3424d9ad7c5a4b35e', -13)
('003423b755b562962a6225a8de40d12e', -15)
('00345f338696283410b7977d2e3efc89', -12)
('0035246a40f520710769010f752e7507', -9)
('0035c0b07126fe9c24a325216fb96064', -27)
('0035e6b7ade84b3f5b86bd49814793df', -15)
('0036757472ece3dde52fd4bfd929c90e', -11)
('0036887767dea4bd43b1a88cd0d9477a', -9)
('00378c6c981f234634c0b9d6128df6dd', 0)
('003822434f91204da0a51fe4cf2aba18', -31)
('0039500db36d50d7d0bfaf23723550f3', -13)
('003a7f59d7e08a9c61d9e2881fe6459c', -2)
('003a94f778ef8cfd50247c8c1b582257', 9)
('003cc6161d7a2593f2525cce0c330d32', -1)
('003d0634280ff3d1d3a54459349a6899', -2)
('003d804eef0e1b856881cd18e0cc0d4c', 23)
('003d9fc84ad902adf2265248b5ffe1a4', -9)
('003edccf16bc5ec447f592913b3df2b4', -1)
('003f201cdd39cdd59b6447cff2195456', 6)
('003f9bcc09427647c4b9d361a523545b', -14)
('00404fa7a687c8c44ca69d42695aae73', -6)
('0040a56893444cb56cba7cfe2225e34e', -7)
('004157daafa0bc8672e01f00e4f0c04f', -24)
('00418a49a685c6bb60633291c3fab17a', -14)
('004345d16a1ab2c21962992c721c8643', -19)
('0044c6f6d22dd280534344177c81b989', -8)
('0045e3085f083f0f38d24bb3f22e6593', -1)
('0045f5225a96ef46630701167528fdcb', -16)
('0046176ff0dbc2a178b7885355dfbb71', -25)
('0046e1d57f4c07c8c92ab26be8c3dfc0', -12)
('00471463a6106056c1a2a809f70de640', -8)
('00482f2670787292280e0a8153d82467', -23)
('0049edf42837aa808e03552a62bd2158', -2)
('004b62108b876867938746ad3154167f', -6)
('004ba47bb589cdbc485e6025bd6d3c81', -21)
('004ca5ae248069d68e8594df8abf6ce0', -41)
('004d76fef3dd46eb4f70da049c8d1f93', -20)
('004eab0fd8f28adaf8d488976f77febe', -12)
('004f5d8f238e8908e6864b874eda3391', 2)
('004fb11815bc03b01b20a614eef69d14', -10)
('004fb5e6f90a178dc74ad2b016649249', -17)
('005059edee63c8c708ba61910793b31b', -15)
('00526a9d4ebde463baee25f386963ddc', 1)
('0055b77cca3186676c147f532dd2547b', -7)
('0057199db02d1a5ef41bacbf41f8f63b', -14)
('00571ded73b3c061925584feab0db425', -13)
('00584d79015452d19fd3d044ba3abdc0', -16)
('00588f5f20fee630b83d4709e0a42715', -30)
('005997dca4c1fc45066d0a03d54a6469', -13)
('005a1dded353107dbabf8ffc83a20365', -5)
('005b49de51a4e006055e8487a50ad8e4', -7)
('005cad6157eadc7f1f09917607f1704a', -7)
('005d9a5423d47281ac463a968b3936fb', -21)
('005e5166e99d1e4d0c4f808b0540ba94', 12)
('005f25968fc854ea16fb16f5bdbc87c7', -3)
('00602f25bffa1dcfb71e202fbf9824fb', -14)
('00611822267e76e0055c25c18506f06e', -20)
('006127b8b9a1681a982313ed7129c3c0', -6)
('0064d74f7de7917d54768d7722ad56ac', -14)
('006557c3221c1fcd02b0106343ab357b', -21)
('00664284de7a3470d22931ed78615ee4', -14)
('0066a1fdaee16ad5022c5ef979d0b661', -30)
('0067c6030d65af0ff98790158ddb0020', -9)
('0068468c453d28c8ef3fd089e50a5847', -6)
('00685d31ae12e47470ba5c18ba74f22c', 8)
('0068c109948b9a1dfb8530d1978acef3', -12)
('0068e836900867da359bd81db9227a33', -19)
('0068fb0e223115e911d362627e8b8800', -21)
('006c42f310102c1910b3c5793ce5fc34', -5)
('006cb7cafc99b29548d4f412c7f9f493', -16)
('006cba07f62f921fe4f58365bde2b2eb', -24)
('006dd93155bc2abd844cc5eed3a0fe7f', -27)
('006df90050498994d670b40da4651d22', -2)
('006e05e81c068ddc38e48ebe189b922e', -21)
('006e43460a55bc60c0a437521e426529', -14)
('006e91ddb0674525f84ce0da0655c7ba', -10)
('006f7dfffe2d90809598e8f1972b829b', -6)
('0070092bb6004faafa287e5fc35971e9', -18)
('0071ee2429bc1efdc43aa3e073a5290e', -15)
('0072847849eafe70995fa51a714c81ac', -7)
('00750f68bb64537034e93554c64b41b5', -13)
('00756576f4e494406945ac21cb82cfe0', -14)
('00772b2af35643653f108fdac1155ee3', -6)
('00789ce015e7e5791c7914f32bb4fad4', -3)
('0078a358a14592b887eb140ef515f5ab', -8)
('0079bca8e89bd52fdb87408e4f3fb94d', -10)
('007bbb40c95870c0f75a7855f2636c65', -11)
('007beb35f98c075747e6fc4fd1c0cb73', -16)
('007c7cb12ef3567531307ca78d395758', -4)
('007ec946d4f798caf2b43c9d44c56421', -20)
('007ff0b0f79be782f633fc3b18cbe337', -16)
('0080eebb288dba1857ccf048dfe6bdfe', -19)
('0081ab2c99dc85945c28926b77dc6960', -10)
('0081ce648af7d6a7bac2a93b6035d1e3', -9)
('0084209c576daad6ff4534902fcb4892', -9)
('0084e195fbd72ae51599af47f04afede', 24)
('00858d03144cc35cfd1dd043647e7c88', -34)
('008720830a8a30e39e6f22f81818a141', -7)
('0087889a1c836be17f58afd7f1729a4a', -10)
('008819c6d5f6da6fa5cd9d50ca927cf4', -2)
('00891ba5de66f55000ee358ceea9b345', -15)
('008990da719764fb392914d8ab53ad04', -14)
('008a1b3db2a8bf63418c2cf7c7f494b1', 10)
('008a40c2b8b21893e04945ce58854b55', -20)
('008c3a655c66f4d92370d0d422732f69', -6)
('008ce8764db2e397e153000e017475b6', -5)
('008cfe221ab054c89bc31720098cca51', -6)
('008d9bf350ff02ed444b3452cf3f57e0', -28)
('008dc31c0ae7121f2791953ae5f532c3', -7)
('008dd5e80ebf8f849aa0c5bf4e22ce7a', -10)
('008eaf9004164883520d0bd32b107261', -18)
('008f831b7185cff7ab35a46c37d64cd2', -18)
('008fab5602c441d51f30b1464f5d4643', -20)
('0091a677651feaf5a08d7bb147681e14', -3)
('00921e4911895b93c7b4fc0d80c0815e', -5)
('0093cbf16a6afb7f0ab7cc821b6f9e92', -13)
('00946f674d880be1f188abc10ad7cf46', -19)
('00949655cdd8d0465e433a5e6c9643e5', -7)
('0094bd07f49fed90209ffa62d1ef26d6', 2)
('0094d4660e323945f84f5c29eb348aae', -18)
('0094dc9ea7e3cd54d95aea42685673ff', -16)
('0095790a64527ec83aeaaf99023c050e', -4)
('0096668e5b0b8e9657a6f7209a4e58b4', 60)
('009742b43f4530bc3db7f62332c50f4b', 26)
('00975e709cd12c34d3bd44e4a7f7a876', -14)
('0097aafe2a01dd54e39888976160c377', -1)
('0097f0545a302aafa32782f1734ff71c', 0)
('009838529bb913846ab6670d22865381', -21)
('0098dbda25722a3f019fe252a0cd10b3', -9)
('009905140e9f8cc35d5be897937381db', -14)
('00995d799817ecc3bd2abd8fbe59c430', -6)
('00998f38df3012359ef195ca75ebb329', -21)
('009ac365164f8e06f59d18a08045f6c4', -14)
('009c278fa2ed6e7ec498200b60193ca8', -9)
('009e11afa25aa95ae78e60a793995c9b', -38)
('009fa9bd0d92710e840793bfefa80867', -3)
('00a0116ff15ff973ea16bee881208ae7', -12)
('00a12754417a49a9dec20361849aa917', -6)
('00a13ab02fbe82f78cd84f14e41564ed', -14)
('00a174dbf11967d260033fa6ab711493', -1)
('00a1e977cf6e672402963940db55d919', -6)
('00a250dbdb3153cc6ecf4d3f07ef6a17', -15)
('00a379dfab816a83741012b71b264098', 2)
('00a3a334aec7455a6d3319981499a3da', -9)
('00a3f1ef430d3984dece2f39d6cbf431', 0)
('00a4d94df1c9757661679b2f4bd6d311', -15)
('00a57dfbb049fbaae10763e2cf15f797', -14)
('00a690becda145533fa5a54daa7b6ad5', -14)
('00a77f9cc25b05b2004752593d7b8888', -7)
('00a843f5a80c7aea894c558acc29f513', -16)
('00a870c6c06346e85335524935c600c0', -7)
('00a9536682ecb394a3794c1608200803', -9)
('00aa423621f35a9ca6c6240f275b0640', -9)
('00ab1aba567dfebdc39caa4e7ca2f1b2', -21)
('00ab210695a17fe10e6b23616ae5bc97', -7)
('00ab3a43bda739029ffce95d3b2fb56c', -1)
('00ab9fa91aafa3d881164b0da48999aa', -19)
('00ac05fe0fc047c54418098eb64e3aaa', -14)
('00ac2a1ec784f71feeb7ba1e5959750d', -20)
('00ace652c8a5072670f30674e5f19844', -15)
('00ad1a02d4d9decad15c7e8f8a9470cc', -18)
('00af3d9ddff7f256e83d79247dbe1a9f', -19)
('00af53fdc2002f5b6a8f16db648e003b', -7)
('00b12f4674177ef40c4bdb034138c843', -13)
('00b1861aeb89afa498404c684148a619', -9)
('00b2d2f2b5f7b98e6b1828764660134e', -15)
('00b30bb163474583c14db1689259cf4d', -16)
('00b402e8a76d3da83714c52d3977cc2d', -12)
('00b44ba3d7c4a5e9a9ebafef9150781d', -27)
('00b47ee856118583dbec7d1f9b18d847', -4)
('00b4846d477a7baf5d4e47970bc08c7e', -17)
('00b4a910f64f24dbcac04fe54088a443', -33)
('00b4c651133c06fb175123a492f1cac3', -5)
('00b5e1c770b1868ec1b6b726be3aa9b9', -15)
('00b676b01c289cc661c6f7732492771a', -9)
('00b6c055922e0ed2d88efdd252b2fb64', -9)
('00b6e66f005a657a6b13eedcacdf9342', -10)
('00b7174ea52bb811ebe2663add51afc0', -18)
('00b8d354b36820e9d6131fd5173c5581', -13)
('00b9e0f8f588d0406a3de447eb606970', 2)
('00ba414462370af2d76195d12e0d5481', -17)
('00ba57ae98928df6ba6ec9d3d8d4b1b7', -14)
('00bbc4179554524748f77763ddd62266', -9)
('00bc78808b22918a467b2fa4b8ef5d68', -13)
('00bcee890eba57a9767c7b5ca12d3a1b', -25)
('00bd2cb7e9076e1ccc9f766fc01a4cfd', -23)
('00bd50cdd31bd22e9081e6e2d5b3577b', -8)
('00bd8cf08fa3998ea6ad6d16c2165822', -21)
('00bdcdda88e6b02977fc6ce3d412c600', -36)
('00bdebefeb760588a3425fad9dfed3d9', -12)
('00beb247698c6aae94e3f859d279e2cd', -13)
('00bf1320ffb5fe47a845feca16c0e0b4', 8)
('00c00d5b36157595e21108ba1da2828f', 7)
('00c2335723b9b74668062e946dc66621', -20)
('00c405bd71187154a7846862f585a9d4', -17)
('00c42b1633c1b2fa4e937bf312466561', -7)
('00c47cfa491ef55779ec7557673087fc', -12)
('00c47fefb9a49baec12ab3654d7f548e', -15)
('00c4f17dcb94448f27a2cbaa83f10a4b', -7)
('00c62d05602c1ca8164b98746d127fa8', -30)
('00c763284c0056eed753352f5559ff0a', -21)
('00c81b6675ef9ecaaff5fc1d6720b96c', -15)
('00c826c901ab01b6f598a8f0c9b56b82', -16)
('00c842d0ae6462afc1d38fc055b02c75', -8)
('00c8be06a8029e300dabd52c7d4c6ad2', -10)
('00c8bfbb0a1224dcdb0180a544247159', -13)
('00c9474e0334f7a4ffc8c3a8bd21a51e', -1)
('00c95282163553a982f38481f9488481', -20)
('00c9d0257381c7e9ec13b4505f25b2cf', -21)
('00c9d9e61ed13f5bf2f0344da1aa4775', -11)
('00c9f7d4b0e87781465e562dc109f6aa', -20)
('00cb18db3d9c03f8386e7fc70cad2504', -15)
('00cb9736c0b43d6c1e2fbb2b88e69f6a', -17)
('00ce92d57f4f9a112bdb8a2a283e5f97', -19)
('00ceda91cb2ded8570ca73e70571740a', -18)
('00cee8a4dbb042385cbbd84699e78b2e', -7)
('00cf2b04c59f0ecaf822bf3f334d5c3b', -7)
('00cf47526e0f7920b381b2baf4ecf1c7', -29)
('00cfabbe2a93b70beeec4894f86712a8', -13)
('00d03eb3425f41a599ae2f788e23c07f', 11)
('00d0ff2017f9ea13dd7eec7470ca473a', -21)
('00d1289d5125017a90e528b5a7cee91f', 74)
('00d15ff0236872686e4899ed1ce680ad', -9)
('00d1e381c0995f0bdb95909fe7434d0b', -11)
('00d2559e61b9a0744a0552c35c5ecccb', -10)
('00d29386638bbfd1331a2cd7ab91b5b5', -14)
('00d4439957b7fd3f8da4a33a965817fb', -8)
('00d50baf1bc56a3c59de1810a6b84b0d', 5)
('00d5fac7792747fba4b528f23930bebd', -13)
('00d831d5c3ea03b7cd6f883ad799c7e4', -9)
('00d85bfe0e28c91b69d0fe1f29255a31', -14)
('00d88c00221ce96a1cfcaca9f2fceb3b', 0)
('00d8d65b666158b633f96054d31af43b', 0)
('00d94e8901b75ee0d6ef1f87f947b666', -13)
('00d9ac423c9ad6781c0ed04e87666691', -10)
('00dc6ad47477b3b62d3c0acbe98a82a4', -12)
('00df27e666004db9f14bce766fa5327c', -14)
('00dfb074b5c910fbd08e04691c4b712f', -25)
('00e054d0da011d5016f31011af488f4f', 41)
('00e0bac9f6306d8269770acf4ee4b027', -2)
('00e1426d4c79f2e022570012c1ff57ed', -12)
('00e1bdb3f1388c8ed222597ee4fa01e7', -14)
('00e32e413e017e64ff93a9e800b8e1be', -16)
('00e365f4fc03d1098841af23d05c17a6', -12)
('00e4050fe32e786290a29c61141e979f', -25)
('00e5b655df1cc911466758210325c67c', -13)
('00e63486fad9d24645c9c84ed77c15fa', -21)
('00e6786fee8f476835c151a4d3fa9bf1', -15)
('00e6bc6b166eb28b4502c1cad4457248', -25)
('00e7aeced1d61792368ec7bf8b967a90', -13)
('00e7ee1b050b8499577073aeb2a297a1', -11)
('00ea33f994bec0bbfda582074083ae12', -16)
('00ea690fe8c5eba029a3884243a02352', -8)
('00eb7b95af5ed25aaec66d4ff5295846', -24)
('00ec95a58b63378d4cc06d196cdefdf6', -16)
('00ed64bc080d87b4ab7f0c433bc5e98f', -15)
('00eead1d5a799277ef3d6b387b0bebef', -7)
('00eef7fe9e315a85d1a61a50cccb2494', -11)
('00ef7ed06a55243f3e6a9d373a89eb14', -18)
('00efb72d8e18533f736e86770705d094', -29)
('00f1a34f176151c4dcbd802c244e1072', -7)
('00f1bb0af030935db1745ee28367ea26', -9)
('00f1c7c1542f5f86c3091749d9e939d8', -20)
('00f1cc7439ccb8671133776d1829faf5', -3)
('00f251b943aba645652c7138e4716fee', -14)
('00f2a3509bd600bd1a06a48353788d93', -25)
('00f2c876aa08fbba04199823952e96c1', -21)
('00f324f6ec332cd73ef8be4888573662', -8)
('00f33ee62c15223679d3550e751c37cd', 0)
('00f426c7214575822c3cb44ea59ef0f6', -19)
('00f57f2ccce2a2e3f393fe8f5e616e0d', -14)
('00f5fbdc777e8198c1ee008122e28ae3', -14)
('00f621226c6f4e938348f6f3a71fdc62', -18)
('00f6ac4816d12f49026b09f2aa77d15f', -14)
('00f6dbc6195397197ee147ee45607a2c', -8)
('00f7c5b41250e0126ced62d612ff4711', -22)
('00f86b368251d739f1896d41469b2b7a', -3)
('00f8fc0cb9d9b7813f1f54fbd75426f1', -12)
('00f98eaeddb9debc8df8cb27e08216d4', -7)
('00f9b0236a85fb8a06fbd9b9c53fddd8', -10)
('00f9b6769c6648ac08bf43081d1f2b07', -25)
('00faa6afcde74aaa630e1d2fda2bb0f7', -14)
('00fb055886536063afa0dbee07a0944f', -20)
('00fb278a99144cc1004b3ed1452ff5e1', -13)
('00fbcd8b120e5706c58b9d1a0026a7da', -1)
('00fc308dd7f0937682698becaa9dcc45', -9)
('00fcf938cde49ae138942b632ed62393', -10)
('00fdb72e467da6f3b000b19b368a6cf6', -24)
('00fe20fc069833ab95021b46d6862646', -31)
('00fed9e582d5a3e38566872eec164ac6', -15)
('010061e3aa0c6ed5e393dda0652bbee8', -3)
('01006620eb4732deec44be4b0d9e33cd', -14)
('010078e0913f48d014483bd856c01ca1', -16)
('01015fb6493ea5b9ba105c80b5452da1', 7)
('0101aea69a09e1aa32caa6dbaba98503', -33)
('01029b44abe6e15c8df48b1b759ab437', -11)
('0103878b7ed86b6ec873cfae01379472', -9)
('01074135a88ffa5978eaadfc7f482f2b', -7)
('0108c64ec135e4a7a75e9b5102af9bfa', -4)
('0108fba93678555ad1cec9c267848187', -12)
('01094e169d4b14edaf6954eeddb83633', -9)
('010a35dc7fc3808a03d243d2fd8c6e35', -14)
('010ab3b1993057e91f825c672375a66d', -21)
('010b0f6bd323a9effd095a743e660f26', -5)
('010b143d83a59b355cd5a75c0f0fd785', -18)
('010c995323bc17d8156fbe2c37fed63e', -13)
('010d14f76a229c295260e4ca4744acc7', -11)
('010d15deea8cae96ae86ea8097917a17', -20)
('010d6db2f77220b394f147836c94f27b', -5)
('010e04b5f879320f29a9bd6ca41abc94', -10)
('010e7dda85fff564e8b7076ae3928efb', -6)
('010ef5b0279d7512e7343cb775e423c0', -14)
('010efe60bdadc9261d1902f3c1dda5f3', -32)
('010f223ddbec749e95ef3f5414f9c4ee', -17)
('010fadb12341d8253d920362fc8f7a16', -1)
('010ff1cfe12f3094577e72b7bcecdf98', -21)
('0110688c40ff035d672af3aac1f38f10', -2)
('011080783e02d05b26c8c158b3653a42', -21)
('011105c3b5b8693eda1bfb1f152cec2a', -24)
('011108c8a3d6eee6807f48a2e639439f', 3)
('01115c06246220def210911556bdc0e5', -1)
('011331376a4c6cc7a9e5bc165ec169d0', -12)
('011375f941b3695c3c3ee58bfe0d3655', -12)
('0113affd907a209209ab08413bb54226', -6)
('0113c9989fe6e5007795daec0633b405', -18)
('011405ae7b89def8ffb3468eb29c299d', -12)
('01144cadcf64b6427f0a6580a3033220', -26)
('0114835d7f0b3f674b70a989411e31c1', -9)
('01156b662f3f47b249b5a8881d205f08', -6)
('0115abf6b892040abfdd5bdfcb6b2c51', 5)
('0115d160c5fbd758a139ff90821db60d', 3)
('0115f8bb1dc16d3fac863ce1deb037b6', -14)
('011667ae100a333a3051c9a23e3f0283', -13)
('011724d1afbd91844302627f79a66800', -7)
('0119e98feb97441cb456c010c25b04ff', -21)
('011a43bc9bb525517251ebb3ebc99b69', -9)
('011a56023faf5bbb9af634e20a85f7bc', -14)
('011abf147a69ba486bae3a74b6cd1814', -14)
('011af0959ebf2b09a062867811dc63b5', -20)
('011b142c9e082a5c1d10e0a88cd9c8e8', -2)
('011b8dd4f8c36fd4fcf50643ce91d58a', -10)
('011bf86f1b7dacebda2c874333cf656b', -15)
('011c899816ea29773525bd3322dbb6aa', -9)
('011e6e76dd0cd56d26b5b0cb036e80a8', -8)
('011f9dff2545a2cf8ac1809faed3ec88', -14)
('011fcb4fabb3e142579ad63472b11227', 7)
('0120e3dd2696a3bbb68dc2860815f7f2', -31)
('01218a8a807fc187849529e6f12237a9', -13)
('0121cfa7c946e6589f50d7012d3eb5eb', -20)
('012219b6d6d034eb359fc74730a080db', -12)
('012248555cb0bf51df99199cef81d562', -13)
('0122e81ff800460e44bb9c983ff2a2fd', -8)
('0123098b96f3d4014545642be53d891c', -8)
('01235dc626dcf13283207ba7f36a959a', -3)
('01237c761ffb72594a466ed514518af0', -15)
('0123a055aa66357326dd6db066592a7d', -11)
('0124e0c5bfae1979838a91e47df53f14', -11)
('0124f01177fc17cf20e1974621fd759a', -11)
('01255808a3d38a8dd69aa93265a4cb88', -18)
('012670c73246a753cbde0a215c2b9e8f', 8)
('0128412231f9fe9d7e944eea5392fc6b', -1)
('012973f4cb6743d00d7e2644ddc8804c', -31)
('012a238ab54294a3b365812ccc82b135', -15)
('012b3f6ab7776a8ab3443a4ad7bef2e6', -20)
('012bea13f9a355c983efb59a3f23583a', -12)
('012d8cbea490e6102cee6a2088aaa785', -20)
('012dc9e42da722d22e32c618a2521bec', -7)
('012e93f8170eb75b2f2f650629d04517', -22)
('012ea594e035047289b3e7c3f8b90cef', -6)
('012eab2625c5f8aaac6f37f2c19ef62f', -13)
('012f255bd5034b8e7fb3c91566a91cc8', -21)
('012f29911fcd2f1209d937741a6bbc6f', -14)
('012f2c4ca09b101a73e18957c3294cd6', -16)
('013037c3f1773cc8fdbaf8ff54d8013b', -16)
('013056cfe49763c6f66bda03396c5ee3', -4)
('01311f2795d8463a11f9422173687696', -10)
('0132158c30672a8c52997a2492613ec2', -15)
('0132451f29a10b66a5cf1bacc85f9afe', -20)
('0132d77609dd6e1867515ec57d898c10', -15)
('0132f39e8ad9b42ad2d41c847f44c0ed', -12)
('0132fef017ccf586491ca3685de667df', -26)
('01336d091c57d8be1feca330c5f047bd', -21)
('0133a47b53fee66218790a8d7dcab993', -20)
('0135675503322d804abef7ec5ed4824b', -17)
('01358622f65717728b3b2ec2cf4e8812', -10)
('0136390286be8a34efdc801ed150568f', -17)
('0136bcc7370d7fdf44bd916a6dd583c6', 1)
('01380d0df5b7dc8bd13f2266a57bd42c', -17)
('013a98b3a668bcef05b98898177f6923', -31)
('013aa6ba5077072401773f83f1ee6408', -5)
('013b811ba81339b7634ab5231c547e6a', -12)
('013bc5ce14f856d31efc8bebdc3a278f', -27)
('013bc77d3ca5fba084a241fdcb307393', 21)
('013d92e415d1de7bf3b3b706f1b6d292', -10)
('01405161cfdf60dd80df1f393a2796d5', -4)
('014176e9538672a32d2a9b73bf53a31f', -10)
('01422b2c3c27fa3bc464e72eaed9676b', -14)
('01428962dce3b65e5433eaeb16c0f48f', -14)
('0143924743f240e1fdcd6a8918fbe147', -10)
('014405982914c2cde2796ddcf0b8703d', -17)
('01442602b15d4127a84ca6ac1507ee2d', -15)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

More than 1 order → 1 (Repeat Customer)
1 order           → 0 (Not Repeat Customer)